-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.bioassay
(
    bioassay_id integer NOT NULL,
    protein_accession text NOT NULL,
    PRIMARY KEY (bioassay_id)
);

CREATE TABLE IF NOT EXISTS public.target
(
    protein_accession text NOT NULL,
    gene_id integer,
    ref_seq text,
    uniprot_id text,
    PRIMARY KEY (protein_accession)
);

CREATE TABLE IF NOT EXISTS public.activity
(
    bioassay_id integer NOT NULL,
    assay_data json,
    PRIMARY KEY (bioassay_id),
	FOREIGN KEY (bioassay_id) REFERENCES public.bioassay (bioassay_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);

CREATE TABLE IF NOT EXISTS public.activity_type
(
    type_id integer NOT NULL,
    type_name text NOT NULL,
    PRIMARY KEY (type_id)
);

CREATE TABLE IF NOT EXISTS public.substance
(
    substance_id integer NOT NULL,
    smiles text NOT NULL,
    PRIMARY KEY (substance_id)
);

CREATE TABLE IF NOT EXISTS public.substance_errors
(
    filename text NOT NULL,
    error_message text NOT NULL,
    PRIMARY KEY (filename)
);

ALTER TABLE IF EXISTS public.bioassay
    ADD FOREIGN KEY (protein_accession)
    REFERENCES public.target (protein_accession) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;